spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql-test
    url: jdbc:mysql://49.234.99.239:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 49.234.99.239
    port: 5672
    username: guest
    password: guest
  redis:
    host: 49.234.99.239
    port: 6379
    password: redis-test
  jpa:
    show-sql: true
girl: 18
