spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql-test
    url: jdbc:mysql://49.234.99.239:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 49.234.99.239
    port: 6379
